api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
urlpatterns = [
    path('', views.apiOverview, name="api-overview"),
	path('entry-list/', views.entrylist ,name='entry-list'),
	path('entry-search/', views.entrysearch ,name='entry-search'),
	path('entry-random/', views.entryrandom ,name='entry-random'),
	path('entry-detail/<int:pk>/', views.entrydeatil ,name='entry-detail'),
	path('entry-create/', views.entrycreate ,name='entry-create'),
	path('entry-update/<int:pk>/', views.entryupdate ,name='entry-update'),
	path('entry-delete/<int:pk>/', views.entrydelete ,name='entry-delete'),
]
urlpatterns = format_suffix_patterns(urlpatterns) # in order to accept URLS like "/entry-details/2.json" or "/entry-details/2.api" or "/entry-list.json"

encyclopedia/urls.py
from django.urls import path

from . import views
app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("edit", views.edit, name="edit"),
    path("randompage", views.randompage, name="randompage"),
    path("new", views.new, name="new"),
    path("wiki/<str:title>", views.article, name="article"),    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('api/', include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

# handler404 = 'encyclopedia.views.handle_404_page'

api/models.py
from django.db import models

# Create your models here.

encyclopedia/models.py
from django.db import models

# Create your models here.
class Entry(models.Model):
	title = models.CharField(max_length=200,blank=False, unique=True)
	content = models.TextField()

	def __str__(self):
		return self.title
	

api/views.py
from rest_framework import status
from rest_framework.reverse import reverse
from .serializers import EntrySerializer, EntryListSerializer
from encyclopedia.models import Entry
from rest_framework.decorators import api_view,authentication_classes, permission_classes
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
import random
# Create your views here.

@api_view(['GET'])
def apiOverview(request):
	api_urls = {
	'List':'/entry-list/',
	'Detail View':'/entry-detail/<int:pk>/',
	'Create':'/entry-create/',
	'Update':'/entry-update/<int:pk>/',
	'Random':'/entry-random/',
	'Search':'/entry-search/?q=<str:search_query>',
	'Delete':'/entry-delete/<int:pk>/',
	}
	return Response(api_urls)

@api_view(['GET'])
def entrylist(request,format=None):
	entrys = Entry.objects.all()
	serializer = EntryListSerializer(entrys,many=True)
	return Response(serializer.data)

@api_view(['GET'])
def entrysearch(request,format=None):
	entrys = Entry.objects.filter(title__contains= request.GET.get('q'))
	serializer = EntryListSerializer(entrys,many=True)
	return Response(serializer.data)

@api_view(['GET'])
def entryrandom(request,format=None):
	lst=[]
	for entry in Entry.objects.all():
		lst.append(entry.id)
	# lst = util.list_entries()
	size = len(lst)
	entry = Entry.objects.get(pk=lst[random.randint(0,size-1)])
	return Response( (EntrySerializer(entry,many=False)).data )


@api_view(['GET'])
def entrydeatil(request,pk,format=None):
	try:	
		entrys = Entry.objects.get(pk=pk)
	except:
		return Response(status=status.HTTP_404_NOT_FOUND)
	serializer = EntrySerializer(entrys,many=False)
	return Response(serializer.data)

@api_view(['POST'])
@authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([IsAuthenticated])
def entrycreate(request,format=None):
	serializer = EntrySerializer(data=request.data)
	if serializer.is_valid():
		serializer.save()
	print(serializer.data)
	return Response(serializer.data)

@api_view(['PUT'])
@authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([IsAuthenticated])
def entryupdate(request,pk,format=None):
	try:	
		entry = Entry.objects.get(pk=pk)
	except:
		return Response(status=status.HTTP_404_NOT_FOUND)
	serializer = EntrySerializer(instance=entry,data=request.data)
	if serializer.is_valid():
		serializer.save()
	return Response(serializer.data)

@api_view(['DELETE'])
@authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([IsAuthenticated])
def entrydelete(request,pk,format=None):
	try:	
		entry = Entry.objects.get(pk=pk)
	except:
		return Response(status=status.HTTP_404_NOT_FOUND)
	# serializer = TaskSerializer(instance=task,data=request.data)
	entry.delete()
	return Response("Item deleted")

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import Http404, QueryDict
from encyclopedia.models import Entry
import random


def index(request):
    entries=[]
    for entry in Entry.objects.all():
        entries.append(entry.title)
    return render(request, "encyclopedia/index.html", {
        "entries": entries
    })

def article(request, title):
    # md = markdown.Markdown()
    try:
        entry = Entry.objects.get(title__exact=title)
    except:
        raise Http404("Article does not exist")     
    
    # content = md.convert(content)
    return render(request,"encyclopedia/article.html",{
        "title": title,
        "content": entry.content
    } )

def search(request):
    name = request.GET.get('q')
    options = []
    valid = Entry.objects.filter(title__contains=name)
    for entry in valid:
        options.append(entry.title)
    print(options)
    return render(request, "encyclopedia/results.html", {
        "content": options
    })

def randompage(request):
    lst=[]
    for entry in Entry.objects.all():
        lst.append(entry.title)
    # lst = util.list_entries()
    size = len(lst)
    entry = lst[random.randint(0,size-1)]
    return redirect('/wiki/'+entry)

def new(request):
    if (request.method=='GET'):
        return render(request,'encyclopedia/new.html')
    elif (request.method=='POST'):
        title = request.POST['title']
        content = request.POST['content']
        method = request.POST.get('_method','')
        title = title.strip()
    
        if (title and content):
            if(method=='PUT'):#check if title is matching
                original = request.POST['original'].strip()
                if( (title!=original) or ( not(content.strip()) ) ) :
                    return render(request,'encyclopedia/new.html', {
                        "error": 1,
                    })
                try:
                    # print(request.POST['original'])
                    e = Entry.objects.get(title__exact=original)
                    e.content = content
                    e.full_clean()
                    e.save()
                except:
                    return render(request,'encyclopedia/new.html', {
                        "error": 1,
                    })
                
                #else valid edit
                return render(request, 'encyclopedia/article.html', {
                    "title": title,
                    "new": 1,
                    "content": content
                })
            #else here when a new page is being created
            try:
                e = Entry.objects.create(title=title, content=content)
                e.full_clean()
                e.save()
            except:
                return render(request,'encyclopedia/new.html', {
                    "title": title,
                    "error": 1,
                    "content": content
                })
            return render(request, 'encyclopedia/article.html', {
                "title": title,
                "new": 1,
                "content": content
            })
        # here if there is blank title or blank content
        return render(request, 'encyclopedia/new.html', {
            "error": 1,
        })
    

def edit(request):
    title = request.GET.get('title')
    try:
        entry = Entry.objects.get(title__exact=title)
    except:
        raise Http404("Article does not exist") 
    
    return render(request, 'encyclopedia/new.html', {
        "title": entry.title,
        "original": entry.content,
        "edit": True
    })

encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}
{% block title %}
    {{title}}
{% endblock %}

{% block body %}
	{% if new == 1 %}
    	<div class="alert alert-success alert-dismissible fade show" role="alert">
	        <strong>Success!</strong>
	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
    	</div>
    {% endif %}

	 <h1>{{title}}</h1> 
	
    {{content | markdown | safe}}
	
	<form action="{% url 'encyclopedia:edit' %}" method="GET">
		<button name="title" class="btn btn-outline-danger" type="submit" value="{{title}}">Edit Page</button>
	</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
           <a href="wiki/{{entry}}">
            <li>{{ entry }}</li>
           </a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
      <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <!-- JS, Popper.js, and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/search", method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Add a new page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div id="body" class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}
{% block title %}
    New Page
{% endblock %}

{% block body %}

    {% if error == 1 %}
    	<div class="alert alert-warning alert-dismissible fade show" role="alert">
	        <strong>Error - inconsistent data was submitted</strong>
	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
    	</div>
    {% endif %}

    <form action="{% url 'encyclopedia:new' %}" method="POST">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-default">Title</span>
            </div>
            <input value="{{ title }}" type="text" name="title" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Enter the content of your entry in <a target="_blank"href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax">Markdown</a> format- </label>
            <textarea name="content" class="form-control" rows="18" placeholder="Content here">{{ original }}</textarea>
        </div>
        {% if edit %}
            <input type="hidden" name="original" value="{{ title }}" />
            <input type="hidden" name="_method" value="PUT" />
            <input class="btn btn-success" type="submit" value="Update">
            <a class="btn btn-danger" href="wiki/{{title}}" role="button">Discard Changes</a>
        {% else %}
            <input class="btn btn-success" type="submit" value="Submit">
        {% endif %}
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <ul>
        {% for entry in content %}
           <a href="wiki/{{entry}}">
            <li>{{ entry }}</li>
           </a>
        {% empty %}
           <li>No Results, for the search query</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/success.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Success!</h1>
    

{% endblock %}